// <auto-generated />
using System;
using HW17.Infrastructure.EfCore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW17.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW17.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auther")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auther = "آنتونیو مارکز",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/images/books/hezaroyekshab.jpg",
                            PageCount = 400,
                            Price = 490000m,
                            Title = "هزار و یک شب"
                        },
                        new
                        {
                            Id = 3,
                            Auther = "لورا هریس",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/images/books/ensan.jpg",
                            PageCount = 820,
                            Price = 620000m,
                            Title = "انسان خداگونه"
                        },
                        new
                        {
                            Id = 2,
                            Auther = "دکتر جان اسمیت",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/images/books/rome.jpg",
                            PageCount = 310,
                            Price = 750000m,
                            Title = "اساطیر جهان"
                        },
                        new
                        {
                            Id = 4,
                            Auther = "مائوریسیو گاند ",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/images/books/ManoBabam-3.jpg",
                            PageCount = 550,
                            Price = 380000m,
                            Title = "قصه های من و بابام"
                        },
                        new
                        {
                            Id = 5,
                            Auther = "دایان وایلد",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/images/books/honar.jpg",
                            PageCount = 940,
                            Price = 550000m,
                            Title = "هنر در گذر زمان"
                        },
                        new
                        {
                            Id = 6,
                            Auther = "دایان وایلد",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/images/books/kherad.jpg",
                            PageCount = 940,
                            Price = 550000m,
                            Title = "انسان خردمند"
                        },
                        new
                        {
                            Id = 7,
                            Auther = "دایان وایلد",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "/images/books/napelon.jpg",
                            PageCount = 940,
                            Price = 550000m,
                            Title = "دایی جان ناپلئون"
                        });
                });

            modelBuilder.Entity("HW17.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "معاصر، کلاسیک",
                            ImagePath = "/images/Category/stack-of-books.png",
                            Name = "رمان و داستان"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "غرب و شرق",
                            ImagePath = "/images/Category/artificial-intelligence.png",
                            Name = "فلسفه و منطق"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "فناوری و تاریخ",
                            ImagePath = "/images/Category/microscope.png",
                            Name = "علمی و تاریخی"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "داستان های مصور",
                            ImagePath = "/images/Category/student.png",
                            Name = "کودک و نوجوان"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "طراحی و نقاشی",
                            ImagePath = "/images/Category/color-pallete.png",
                            Name = "هنر و معماری"
                        });
                });

            modelBuilder.Entity("HW17.Domain.Entities.Book", b =>
                {
                    b.HasOne("HW17.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HW17.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
